# Generated by Django 4.2.4 on 2023-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two Wheeler'), ('Three', 'Three Wheeler'), ('Four', 'Four Wheeler')], max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
