# Generated by Django 4.2.4 on 2023-08-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_details',
            name='vehicle_description',
            field=models.TextField(null=True),
        ),
    ]
